# Generated by Django 5.1.4 on 2024-12-21 03:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0002_complaint_image_complaint_location'),
    ]

    operations = [
        migrations.RenameField(
            model_name='complaint',
            old_name='engineer',
            new_name='assigned_engineer',
        ),
        migrations.RenameField(
            model_name='complaint',
            old_name='image',
            new_name='photo',
        ),
        migrations.AddField(
            model_name='complaint',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
