# Generated by Django 5.1.4 on 2024-12-22 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0006_alter_complaint_latitude_alter_complaint_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='country',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='complaint',
            name='pincode',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='complaint',
            name='state',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='complaint',
            name='suburb',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
